### PR TITLE
[Bug] Go-Table Change Selectable Issue

### LINKED ISSUE #774: [BUG] Table Change Selection Behavior
**Describe the bug**
On the `go-table`, when the table renders with `selectable: false` on the `tableConfig` the table renders fine. However, after it renders fine, if the `tableConfig` is reset with `selectable: true` then the selection behavior / events of the table are completely broken. 

**To Reproduce**
https://stackblitz.com/edit/goponents-table-change-selection-issue

**Expected behavior**
We should be able to switch the table between a selectable and not selectable state and have it work as intended regardless.

**Screenshots**
N/A

### PR DESCRIPTION
**Pull request by grahamhency**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our [guidelines](https://github.com/mobi/goponents/blob/master/CONTRIBUTING.md)
- [ ] Tests for the changes have been added
~~Docs have been added or updated~~

## PR Type
What kind of change does this PR introduce?

- [x] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] Style Update (CSS)
- [ ] Other... Please describe:

## What is the current behavior?
See the issue referenced below for description of problem.
Resolves #774 

## What is the new behavior?
The table will handle when it becomes `selectable` after not being `selectable` and vice versa.

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

### CODE REVIEW

File: projects/go-lib/src/lib/components/go-table/go-table.component.ts [hunk 1]
```diff
@@ -107,6 +107,7 @@ export class GoTableComponent implements OnInit, OnChanges, OnDestroy, AfterView
 
   private destroy$: Subject<void> = new Subject();
   private pageChange$: Subject<void> = new Subject();
+  private selectionSubscriptions: Subscription = new Subscription();
```
Comment (StevenUlmer) [inline projects/go-lib/src/lib/components/go-table/go-table.component.ts:110]: I think everywhere else we've been adding a subject like `pageChange$` to track and remove subscriptions. Should we use the same here?

Comment (StevenUlmer) [inline projects/go-lib/src/lib/components/go-table/go-table.component.ts:110]: Do we need to clean up this subscription in the `ngOnDestroy` method?

**Review by StevenUlmer — CHANGES_REQUESTED** [review]
Really the only concern here is around cleaning up the subscription on destroy. Could we also get a test around this change?

**Comment by grahamhency** [comment]
@StevenUlmer I changed the approach up a bit to the `Subject` approach. I also added tests for this. Ready for another review.

**Review by StevenUlmer — APPROVED** [review]
Looks good. Thanks for adding the tests
