### PR TITLE
File Upload Files Undefined

### LINKED ISSUE #308: ERROR TypeError: Cannot read property 'files' of undefined
**Describe the bug**

**To Reproduce**
1. Add  'go-file-upload' component in application
2. Click on 'Upload Files'
3. Inspect the element and see error.

**Expected behavior**
File upload is not happening as expected.

**Screenshots**
Please find the attachment.
image

### PR DESCRIPTION
**Pull request by StevenUlmer**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/mobi/goponents/blob/master/CONTRIBUTING.md
- [x] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [x] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] Other... Please describe:

## What is the current behavior?
Issue Number: https://github.com/mobi/goponents/issues/308

## What is the new behavior?
Depending on how we're getting the files (dragging and dropping vs clicking on the upload) the events from the html come with different attributes. This fixes the attribute properties for clicking on the upload

Fixes #308 

## Does this PR introduce a breaking change?
- [ ] Yes
- [x] No

### CODE REVIEW

File: projects/go-lib/src/lib/components/go-file-upload/go-file-upload.component.ts [hunk 1]
```diff
@@ -37,7 +37,8 @@ export class GoFileUploadComponent implements OnInit {
   }
 
   onFilePicked(evt: any): void {
-    const files: File[] = evt.dataTransfer.files;
+    const files: File[] = evt.dataTransfer ? evt.dataTransfer.files : evt.target.files;
```
Comment (grahamhency) [inline projects/go-lib/src/lib/components/go-file-upload/go-file-upload.component.ts]: Nice, relatively easy fix.
